name: Build Windows Plugin

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Compile and Link Plugin (.dll)
      shell: bash
      run: |
        mkdir -p bin
        
        # Подключаем встроенный 32-битный компилятор
        export PATH="/c/msys64/mingw32/bin:$PATH"
        
        # Добавляем флаг -include cstdint -include cstddef, чтобы починить ошибки SAMP SDK
        FIX_FLAGS="-include cstdint -include cstddef"
        
        echo "=== Сборка SDK ==="
        g++ -m32 -c -O2 -w -std=c++11 $FIX_FLAGS src/SDK/*.cpp -Isrc -Isrc/SDK
        
        echo "=== Сборка плагина ==="
        g++ -m32 -c -O2 -w -std=c++11 $FIX_FLAGS src/*.cpp -Isrc -Isrc/SDK
        
        echo "=== Линковка DLL ==="
        g++ -m32 -shared -O3 -o bin/DisableVehicleLimit.dll *.o
        
        rm *.o
        echo "=== Готово! ==="

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: samp-plugin-windows
        path: bin/DisableVehicleLimit.dll
